In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import *
import tensorflow_datasets as tfds

In [70]:
class ZeroMask():
    """
    when this class is initialized, it will will initilize a mask. When the instance is called an input 
    array the same shape as the mask will be multiplied with the mask and returned. The returned array will
    be masked to 0 at indecies specified in the "zero_indices" input. 
    
    Having this as a call able class, lets us repeativly use a mask multiple times in a cleanly abstracted way.
    """
    def __init__(self, shape, zero_indices):
        """
        inputs:
            shape: shape of matrix, ei (channels, filters, kernals, x_dims, y_dims)
            zero_indices: list of tuples that specify indexes to be masked to 0, ei [(row, col, channel, filter)]
                if zero_indices is equal to [(r, col, ch, f)] then mask[r, col, ch, f] will be set to 0
        instance variables
        """
        self.mask = np.ones(shape)
        for index in zero_indices:
            self.mask[index] = 0.  
    def __call__(self, arr):
        assert arr.shape == self.mask.shape, "Incorrect dims, mask shape: {}, arr shape{}".format(self.mask.shape, arr.shape)
        return self.mask * arr


In [71]:
mask_func = ZeroMask(shape = (3, 3, 1, 7), zero_indices = [(0, 0, 0, 0), (2, 2, 0, 0), (2, 0, 0, 0), (0, 2, 0, 0)])

In [72]:
(ds_train, ds_test), ds_info = tfds.load(
    'mnist',
    split=['train', 'test'],
    shuffle_files=True,
    as_supervised=True,
    with_info=True,
)
def normalize_img(image, label):
  """Normalizes images: `uint8` -> `float32`."""
  return tf.cast(image, tf.float32) / 255., label

ds_train = ds_train.map(
    normalize_img, num_parallel_calls=tf.data.AUTOTUNE)
ds_train = ds_train.cache()
ds_train = ds_train.shuffle(ds_info.splits['train'].num_examples)
ds_train = ds_train.batch(128)
ds_train = ds_train.prefetch(tf.data.AUTOTUNE)

ds_test = ds_test.map(
    normalize_img, num_parallel_calls=tf.data.AUTOTUNE)
ds_test = ds_test.batch(128)
ds_test = ds_test.cache()
ds_test = ds_test.prefetch(tf.data.AUTOTUNE)

In [112]:
#custom conv layer
class IregConv2D(tf.keras.Model): # still needs to figure out backprop, keep kernal wieghts at 0!!.
    def __init__(self, zero_mask, filters, kernel_size, *args, **kwargs):
        super(IregConv2D, self).__init__()
        self.conv = Conv2D(filters = filters, kernel_size = kernel_size, *args, **kwargs)
        self.zero_mask = zero_mask
    def call(self, x):
        return self.conv(x)
    def build(self, input_shape):
        super(IregConv2D, self).build(input_shape)
        weights = self.conv.get_weights()
        weights[0] = self.zero_mask(weights[0]) # set weights to 0 here
        self.conv.set_weights(weights)
        print(self.get_weights())
    def get_conv(self):
        return self.conv
    
## simple mnist network

class TestNet(tf.keras.Model):
    def __init__(self):
        super(TestNet, self).__init__()
        self.conv = IregConv2D(mask_func, filters = 7, kernel_size = (3, 3), activation = 'relu')
        self.flatten = Flatten()
        self.dense = Dense(32, activation = 'relu')
        self.head = Dense(10, activation = 'softmax')
    
    def call(self, x):
        x = self.conv(x)
        x = self.flatten(x)
        x = self.dense(x)
        x = self.head(x)
        return x

In [113]:
x = tf.keras.Input(shape = (28, 28))
model = TestNet()

In [114]:
def grad(model, inputs, targets):
    with tf.GradientTape() as tape:
        loss_value = loss(model, inputs, targets, training=True)
    return loss_value, tape.gradient(loss_value, model.trainable_variables)

In [115]:
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
def loss(model, x, y, training):
    # training=training is needed only if there are layers with different
    # behavior during training versus inference (e.g. Dropout).
    y_ = model(x, training=training)

    return loss_object(y_true=y, y_pred=y_)
optimizer = Adam()

In [116]:
train_loss_results = []
train_accuracy_results = []

num_epochs = 1

for epoch in range(num_epochs):
    epoch_loss_avg = tf.keras.metrics.Mean()
    epoch_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()
    
    # Training loop - using batches of 32
    for x, y in ds_train:
        # Optimize the model
        loss_value, grads = grad(model, x, y)
        grads[0] = mask_func(grads[0]) ###this is the important part here!!
        optimizer.apply_gradients(zip(grads, model.trainable_variables))
        # Track progress
        epoch_loss_avg.update_state(loss_value)  # Add current batch loss
        # Compare predicted label to actual label
        # training=True is needed only if there are layers with different
        # behavior during training versus inference (e.g. Dropout).
        epoch_accuracy.update_state(y, model(x, training=True))

    # End epoch
    train_loss_results.append(epoch_loss_avg.result())
    train_accuracy_results.append(epoch_accuracy.result())

    if epoch % 50 == 0:
        print("Epoch {:03d}: Loss: {:.3f}, Accuracy: {:.3%}".format(epoch,
                                                                epoch_loss_avg.result(),
                                                                epoch_accuracy.result()))

[array([[[[-0.        ,  0.2583604 , -0.06744356,  0.07393333,
           0.08499187,  0.0345456 ,  0.26686954]],

        [[ 0.16667655,  0.21842569,  0.2051959 ,  0.11701426,
          -0.09301087, -0.21842128, -0.25044236]],

        [[ 0.        , -0.1593098 , -0.13538757,  0.12862182,
           0.03625143,  0.1379807 ,  0.00132874]]],


       [[[ 0.19055638,  0.25506288,  0.04876301, -0.07887872,
          -0.2645274 , -0.22109315, -0.07971083]],

        [[ 0.25541568, -0.0160954 ,  0.12995818,  0.0807198 ,
          -0.2753123 ,  0.0581347 , -0.23939303]],

        [[ 0.04594359, -0.00056967,  0.2708329 , -0.17134649,
          -0.0814804 , -0.2593218 , -0.08769596]]],


       [[[-0.        , -0.18986523, -0.17994967, -0.15135096,
          -0.01983565,  0.256046  , -0.08410347]],

        [[ 0.27390897, -0.10320137, -0.00517026,  0.1962828 ,
           0.25061077,  0.2574649 ,  0.06720707]],

        [[-0.        ,  0.14445561,  0.28609192, -0.17702708,
          -0.20515537

tf.Tensor(
[[[[-0.00000000e+00 -1.70008421e-01 -7.54460171e-02 -1.36452496e-01
    -1.54245785e-02 -3.43228132e-02 -1.65037084e-02]]

  [[-1.25313014e-01 -1.66545570e-01 -1.11122742e-01 -1.32046923e-01
    -1.05286976e-02 -5.79053126e-02 -1.73539156e-04]]

  [[-0.00000000e+00 -1.25135183e-01 -1.35227323e-01 -1.19358376e-01
    -1.05692465e-02 -6.91911057e-02 -3.99219524e-03]]]


 [[[-1.56355590e-01 -1.64138198e-01 -1.11951455e-01 -9.47211683e-02
    -1.26663782e-03 -7.83466473e-02 -1.03022056e-02]]

  [[-1.33367538e-01 -1.45137817e-01 -1.49436101e-01 -8.14428031e-02
    -5.92178258e-05 -9.68498290e-02 -8.16008262e-03]]

  [[-1.14478707e-01 -9.81660932e-02 -1.59672230e-01 -6.72826841e-02
    -4.24910977e-05 -1.00234576e-01 -2.65163053e-02]]]


 [[[-0.00000000e+00 -1.10625826e-01 -1.32738531e-01 -4.37287726e-02
    -1.66391060e-02 -1.26253843e-01 -2.10138038e-02]]

  [[-1.15311317e-01 -9.04672593e-02 -1.72720373e-01 -2.82132197e-02
    -1.21799856e-02 -1.42520592e-01 -2.86663137e-02]]

 

tf.Tensor(
[[[[-0.13916841 -0.20609142 -0.0538162  -0.17392716 -0.03215959
    -0.07134042 -0.01705373]]

  [[-0.14607055 -0.20155859 -0.105952   -0.19515494 -0.01632323
    -0.08510041 -0.00131404]]

  [[-0.12184878 -0.16129051 -0.14341928 -0.17737529 -0.01629901
    -0.07462834 -0.01922714]]]


 [[[-0.19669028 -0.21639428 -0.11354886 -0.14790775 -0.0018324
    -0.11940573  0.00025485]]

  [[-0.19190052 -0.20044461 -0.1758458  -0.14971322 -0.0005002
    -0.11876032  0.00293817]]

  [[-0.1642609  -0.16826445 -0.19781137 -0.12969455 -0.00085833
    -0.10507122 -0.0386401 ]]]


 [[[-0.20503119 -0.17139131 -0.1490668  -0.08848646 -0.02314051
    -0.1867575  -0.01172412]]

  [[-0.19557121 -0.15151867 -0.20580165 -0.08182108 -0.02228701
    -0.18775326 -0.03470959]]

  [[-0.1755716  -0.12928025 -0.21186703 -0.06379674 -0.01479755
    -0.17015812 -0.08802865]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.20609142 -0.0538162  -0.17392716 -0.03215959
    -0.07134042 -0.0

tf.Tensor(
[[[[-1.25463337e-01 -1.54887348e-01 -5.01303934e-02 -1.36526152e-01
    -2.97065265e-02 -4.50658277e-02 -1.95523202e-02]]

  [[-1.44687504e-01 -1.51026100e-01 -9.74916518e-02 -1.65271908e-01
    -1.75105892e-02 -7.84930736e-02 -7.87799619e-03]]

  [[-1.27155721e-01 -1.20302536e-01 -1.26631051e-01 -1.58199146e-01
    -1.91576779e-02 -7.08437786e-02 -3.35171260e-02]]]


 [[[-1.55075163e-01 -1.43343836e-01 -8.76661837e-02 -1.16073661e-01
    -3.37189459e-03 -8.92220512e-02  5.85006783e-04]]

  [[-1.64048493e-01 -1.32976905e-01 -1.36039644e-01 -1.35262549e-01
    -1.13321657e-04 -1.21798277e-01 -1.16510047e-02]]

  [[-1.41875029e-01 -1.16194993e-01 -1.52127877e-01 -1.15341038e-01
    -1.17920805e-04 -1.15887791e-01 -6.60127923e-02]]]


 [[[-1.45010352e-01 -1.13470659e-01 -9.31377858e-02 -8.84754956e-02
    -4.59614694e-02 -1.43122807e-01 -1.11790933e-02]]

  [[-1.54169589e-01 -1.06866822e-01 -1.46502391e-01 -8.98059011e-02
    -3.76252085e-02 -1.67035460e-01 -4.98322733e-02]]

 

tf.Tensor(
[[[[-0.0655995  -0.11384997 -0.0576046  -0.09122033 -0.03091218
    -0.02387799 -0.00108994]]

  [[-0.07632278 -0.09871401 -0.10137017 -0.10696322 -0.02179318
    -0.04105441  0.01175094]]

  [[-0.07458499 -0.06126305 -0.1137453  -0.09236564 -0.02521107
    -0.04304739 -0.00864576]]]


 [[[-0.10163519 -0.1264615  -0.08346894 -0.09122951 -0.00686216
    -0.06205247  0.00651475]]

  [[-0.10646538 -0.10508853 -0.12950924 -0.08707985 -0.00068058
    -0.07322839  0.00653028]]

  [[-0.09666525 -0.07880178 -0.14634755 -0.05999214 -0.00086207
    -0.06633221 -0.02986849]]]


 [[[-0.12724072 -0.11651057 -0.09657517 -0.06866208 -0.03408604
    -0.09930964 -0.00758976]]

  [[-0.13058248 -0.1049986  -0.14953688 -0.0599063  -0.0266596
    -0.11216609 -0.02336041]]

  [[-0.11789755 -0.08960116 -0.17044964 -0.0359696  -0.01393517
    -0.09076392 -0.06129783]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.11384997 -0.0576046  -0.09122033 -0.03091218
    -0.02387799 -0.

tf.Tensor(
[[[[-0.06841047 -0.05210389 -0.07529434 -0.0431045  -0.00364879
    -0.03514264  0.01386086]]

  [[-0.0819755  -0.05947004 -0.09673654 -0.0556351   0.00093888
    -0.0515072   0.0132513 ]]

  [[-0.07967521 -0.04733977 -0.11271482 -0.04820225  0.0058591
    -0.05750723 -0.01116982]]]


 [[[-0.06682936 -0.03239911 -0.05375293 -0.03407442 -0.00103611
    -0.05169357  0.01092695]]

  [[-0.07349746 -0.04296555 -0.07986748 -0.03337988  0.00170134
    -0.07098255  0.00046637]]

  [[-0.06995167 -0.03118737 -0.09347382 -0.02404416  0.00824451
    -0.07884413 -0.03490941]]]


 [[[-0.04700764 -0.01841133 -0.03252976 -0.02380583 -0.02624658
    -0.05990375 -0.00956751]]

  [[-0.05218111 -0.02321089 -0.05633401 -0.0222021  -0.01380485
    -0.07775936 -0.0260381 ]]

  [[-0.04708771 -0.01147027 -0.0746562  -0.01697406 -0.00631097
    -0.07630523 -0.05731184]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.05210389 -0.07529434 -0.0431045  -0.00364879
    -0.03514264  0.

tf.Tensor(
[[[[-0.0448054  -0.03864342 -0.03518342 -0.02583231 -0.04340577
    -0.06044095  0.01382253]]

  [[-0.04213604 -0.04439563 -0.03806982 -0.03193746 -0.04687683
    -0.04369788  0.0187362 ]]

  [[-0.03676452 -0.03978962 -0.02819065 -0.03773741 -0.05969705
    -0.0352972   0.01374901]]]


 [[[-0.02269956 -0.02818708 -0.00240505 -0.01878999 -0.01121912
    -0.05774227  0.03286396]]

  [[-0.0228819  -0.03685903 -0.00590585 -0.02595707 -0.00856877
    -0.048882    0.03836413]]

  [[-0.02879423 -0.03086282 -0.00833782 -0.0248051  -0.01962116
    -0.03493239  0.02065236]]]


 [[[-0.00805402 -0.00825788  0.01810694 -0.00767759 -0.06392653
    -0.05453727  0.04237664]]

  [[-0.0141804  -0.00591166  0.01758338 -0.00346398 -0.06272276
    -0.05146015  0.04427396]]

  [[-0.02670915 -0.00520384  0.00832568 -0.00487618 -0.04892485
    -0.03123341  0.02692067]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.03864342 -0.03518342 -0.02583231 -0.04340577
    -0.06044095  0

tf.Tensor(
[[[[-4.2979822e-02 -6.2030748e-02 -3.2542486e-02 -4.4212952e-02
    -1.0263048e-02  5.0056456e-03  1.3965703e-02]]

  [[-4.9445741e-02 -6.4583331e-02 -4.0478591e-02 -4.4826664e-02
    -1.4599089e-02 -1.4374157e-02  1.9114565e-02]]

  [[-4.4588417e-02 -5.4474443e-02 -5.3882495e-02 -3.7121933e-02
    -5.6879083e-03 -2.0068428e-02  5.6476928e-03]]]


 [[[-5.3423084e-02 -6.0042337e-02 -4.1094817e-02 -3.0277375e-02
     2.4656879e-03 -2.2557817e-02  7.3546115e-03]]

  [[-5.9400685e-02 -6.5418929e-02 -4.8371337e-02 -3.2970294e-02
     7.7461707e-03 -3.8102135e-02  6.8585956e-03]]

  [[-5.5160485e-02 -5.9272401e-02 -6.3365862e-02 -2.0467412e-02
     1.9780921e-02 -3.6651503e-02 -1.8950418e-02]]]


 [[[-5.4006301e-02 -4.5788098e-02 -4.1891806e-02 -1.0410236e-02
    -9.5412717e-05 -4.7891840e-02 -1.1686474e-02]]

  [[-5.8327831e-02 -5.8040489e-02 -4.8772268e-02 -9.6796937e-03
     1.5785541e-02 -5.8662895e-02 -2.1922849e-02]]

  [[-5.9756760e-02 -5.8272019e-02 -6.5140031e-02 -7.24287

tf.Tensor(
[[[[-0.03020217 -0.03683141 -0.00844973 -0.03374602 -0.03519756
    -0.02008242  0.00141801]]

  [[-0.04767595 -0.04559369 -0.01359343 -0.04922202 -0.04396408
    -0.02602109  0.00729363]]

  [[-0.0611855  -0.05628578 -0.02150463 -0.06441902 -0.04312881
    -0.0289381  -0.00232072]]]


 [[[-0.02586951 -0.02937451 -0.00271379 -0.01513313 -0.00444316
    -0.02821804  0.00287189]]

  [[-0.04950275 -0.03938919 -0.01127766 -0.02549429  0.00374313
    -0.04178811  0.00358097]]

  [[-0.06857137 -0.05721295 -0.027025   -0.03651779  0.0016493
    -0.04521673 -0.01934119]]]


 [[[-0.01293982 -0.01305241  0.00988889  0.01252113 -0.03941118
    -0.0427307   0.00122887]]

  [[-0.03846484 -0.02558579  0.000155    0.00583818 -0.02501477
    -0.05735946 -0.00723524]]

  [[-0.05265517 -0.04577454 -0.01583799 -0.0092615  -0.02500644
    -0.0585185  -0.02702242]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.03683141 -0.00844973 -0.03374602 -0.03519756
    -0.02008242  0.

tf.Tensor(
[[[[-0.02004885 -0.0484734   0.00683527 -0.03515637 -0.02721296
     0.02986261  0.00474678]]

  [[-0.04057921 -0.06033403 -0.00951365 -0.05031647 -0.02960498
     0.00729858 -0.00200332]]

  [[-0.05984311 -0.07218888 -0.03426298 -0.05856446 -0.01692718
    -0.02328775 -0.01653932]]]


 [[[-0.03091026 -0.04701386 -0.00448569 -0.03915814 -0.00788938
     0.00537852  0.00398578]]

  [[-0.0497141  -0.06010967 -0.02437585 -0.04890545 -0.00113585
    -0.01797187 -0.01572953]]

  [[-0.07368802 -0.06472818 -0.04915577 -0.03951822  0.00486142
    -0.0459643  -0.03648987]]]


 [[[-0.03791865 -0.04169216 -0.00656667 -0.03979275 -0.03564523
    -0.01798773 -0.01029683]]

  [[-0.05582999 -0.04881483 -0.03223456 -0.03954175 -0.02908794
    -0.04650322 -0.04296011]]

  [[-0.06456647 -0.04966311 -0.05402299 -0.02992839 -0.0221575
    -0.06724939 -0.06394836]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.0484734   0.00683527 -0.03515637 -0.02721296
     0.02986261  0.

tf.Tensor(
[[[[ 0.00627783 -0.01383447  0.02892509 -0.0032491  -0.06664422
    -0.0075045   0.01192508]]

  [[ 0.01162653 -0.01923524  0.03531503  0.00035293 -0.07403359
    -0.00524354  0.02185978]]

  [[ 0.00438842 -0.0264359   0.03663064 -0.01040125 -0.07384221
    -0.01113652  0.03849123]]]


 [[[-0.00560154 -0.02152419  0.01986052  0.00148804 -0.01927407
    -0.00815451  0.00932769]]

  [[-0.00631237 -0.03505477  0.02410293  0.00465999 -0.00860876
    -0.00409598  0.01763941]]

  [[-0.01730069 -0.05525273  0.01886514 -0.00054034 -0.00884859
    -0.00088983  0.02516053]]]


 [[[-0.01574475 -0.01506276  0.01171466  0.01696067 -0.07791292
    -0.02497413 -0.00184807]]

  [[-0.01949521 -0.0365092   0.0110387   0.02292005 -0.06449911
    -0.01902384 -0.0029827 ]]

  [[-0.03229362 -0.07015362 -0.00108191  0.01335333 -0.05383461
    -0.01247865  0.00241453]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.         -0.01383447  0.02892509 -0.0032491  -0.06664422
    -0.0075045   0

tf.Tensor(
[[[[-0.0242727  -0.02602508 -0.00267135 -0.02547202 -0.03549329
     0.00104097 -0.01274342]]

  [[-0.02542118 -0.03431568 -0.00236421 -0.04553139 -0.04348541
    -0.00538929  0.00435163]]

  [[-0.02972684 -0.03086953 -0.00995321 -0.0523521  -0.04519642
    -0.00856847  0.01023621]]]


 [[[-0.01400296 -0.01855832  0.00480958 -0.03074776 -0.00717356
    -0.01202574 -0.00981603]]

  [[-0.02179364 -0.03350152 -0.00224773 -0.05155221 -0.00148497
    -0.02345813 -0.00108326]]

  [[-0.02784327 -0.02887035 -0.01793699 -0.05108842 -0.00930438
    -0.03290811 -0.00645506]]]


 [[[-0.00778445 -0.00796096  0.00899071 -0.0337185  -0.03549834
    -0.01878501 -0.00652982]]

  [[-0.01932887 -0.01452121 -0.00118626 -0.04143229 -0.0371842
    -0.0348329  -0.00549514]]

  [[-0.02809038 -0.00885025 -0.01262071 -0.03480887 -0.03955181
    -0.04277901 -0.01628054]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.02602508 -0.00267135 -0.02547202 -0.03549329
     0.00104097 -0.

tf.Tensor(
[[[[-0.01445467 -0.03667122 -0.01944802 -0.01314961  0.02631224
    -0.01880093 -0.00275749]]

  [[-0.03723223 -0.0467611  -0.03817237 -0.03769246  0.02122752
    -0.02007267  0.00181104]]

  [[-0.04173074 -0.04708331 -0.04979778 -0.03452261  0.05259015
    -0.01678878  0.00193845]]]


 [[[-0.03545617 -0.05944247 -0.02821258 -0.03518841  0.02326264
    -0.02306524  0.00735197]]

  [[-0.05580214 -0.06573054 -0.04841605 -0.04877283  0.04102843
    -0.0302656   0.00934439]]

  [[-0.05905779 -0.05237191 -0.0580661  -0.04342119  0.0671081
    -0.02591167 -0.00462577]]]


 [[[-0.05308425 -0.06784443 -0.03060636 -0.05187096  0.02619366
    -0.02636094  0.01248614]]

  [[-0.06541529 -0.06448297 -0.05527818 -0.0538475   0.06320519
    -0.03805442  0.00245067]]

  [[-0.06292847 -0.04743671 -0.06616223 -0.03605463  0.06883626
    -0.03193712 -0.02423805]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.03667122 -0.01944802 -0.01314961  0.02631224
    -0.01880093 -0.

tf.Tensor(
[[[[-0.03490673 -0.00834402 -0.05646993 -0.00944217  0.01965276
    -0.03571421 -0.01155297]]

  [[-0.01618513  0.00371072 -0.03555474 -0.00306698 -0.01200813
    -0.02842361 -0.0037286 ]]

  [[-0.00243801 -0.00096752 -0.0148975  -0.00641798 -0.02174749
    -0.02263051 -0.00972317]]]


 [[[-0.00625842  0.00878142 -0.02966595  0.00579724  0.02586565
    -0.02846967 -0.0016049 ]]

  [[ 0.00339604  0.01259254 -0.01207873  0.00903476  0.00669147
    -0.01943317 -0.00278694]]

  [[ 0.00986964  0.00102626  0.00543902  0.00197395 -0.00832963
    -0.01873203 -0.02011116]]]


 [[[ 0.01205293  0.02235071 -0.00605293  0.02117596  0.00227759
    -0.01415076  0.01371609]]

  [[ 0.01543936  0.01346063  0.00872449  0.01890393 -0.01287902
    -0.00836501  0.00431434]]

  [[ 0.01530098  0.00140547  0.02646695  0.00989143 -0.01946948
    -0.0167877  -0.01311557]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.00834402 -0.05646993 -0.00944217  0.01965276
    -0.03571421 -0

tf.Tensor(
[[[[-0.04242889 -0.01919099 -0.03845305 -0.02088612  0.01389181
    -0.03755375 -0.01599881]]

  [[-0.0416273  -0.01299328 -0.04985286 -0.01084232  0.00075131
    -0.03422118  0.00094181]]

  [[-0.02506758  0.01043712 -0.04060492  0.0134143   0.01229057
    -0.02916074  0.00085104]]]


 [[[-0.02573731  0.00815993 -0.02579823 -0.00170943  0.01618597
    -0.04442094 -0.00937545]]

  [[-0.02288115  0.02319784 -0.0326617   0.01429861  0.01893104
    -0.03773053 -0.00224323]]

  [[ 0.00339397  0.04026708 -0.01975017  0.03519899  0.03478795
    -0.02186053 -0.0068557 ]]]


 [[[-0.00789372  0.03562535 -0.0047034   0.01397275  0.01216826
    -0.03203267 -0.0115252 ]]

  [[ 0.00757096  0.04551638 -0.00893726  0.02274411  0.0344637
    -0.0205448  -0.01069823]]

  [[ 0.03009349  0.0535152   0.00469835  0.03700772  0.04185446
     0.00130512 -0.01279321]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.01919099 -0.03845305 -0.02088612  0.01389181
    -0.03755375 -0.

tf.Tensor(
[[[[-0.02178045  0.00628883 -0.0151195  -0.03154591  0.03882276
     0.01512225 -0.00171057]]

  [[-0.02276552 -0.00104407 -0.01038363 -0.03559908  0.02469929
     0.01439968 -0.00065886]]

  [[-0.02535147 -0.00641018 -0.0041675  -0.02974935  0.03525138
     0.01533168  0.00485267]]]


 [[[-0.03759221 -0.01257842 -0.01571755 -0.0297127   0.03179528
     0.00577718  0.01912125]]

  [[-0.039738   -0.0209366  -0.01718197 -0.02858953  0.03959319
    -0.00146684  0.01283814]]

  [[-0.04869512 -0.02618133 -0.01800322 -0.02598206  0.04390083
     0.00357052  0.00209619]]]


 [[[-0.04220023 -0.01875756 -0.02709621 -0.0039543   0.03391295
    -0.010125    0.01811466]]

  [[-0.04652705 -0.03355743 -0.03100853 -0.00386954  0.05697022
    -0.01531586  0.00354391]]

  [[-0.05895146 -0.03599112 -0.03254724 -0.01291841  0.03732732
    -0.0108516  -0.00603442]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.          0.00628883 -0.0151195  -0.03154591  0.03882276
     0.01512225 -0

tf.Tensor(
[[[[ 0.00148585  0.02515619 -0.01467629  0.01744147 -0.03257047
    -0.025888    0.00798568]]

  [[-0.00054656  0.0302981  -0.00788764  0.02280527 -0.03340444
    -0.03122231  0.00111103]]

  [[-0.00057499  0.0248749  -0.00134202  0.03271897 -0.03757684
    -0.04003591  0.00366934]]]


 [[[ 0.021801    0.05475017  0.02547332  0.03475334 -0.01043394
    -0.00906782  0.01998997]]

  [[ 0.01667453  0.04827234  0.02835461  0.04375923 -0.00555138
    -0.01846281  0.00585909]]

  [[ 0.02464568  0.04522002  0.02767714  0.04963623 -0.01334813
    -0.02344816  0.00523665]]]


 [[[ 0.05494002  0.0669852   0.0633144   0.03076691 -0.03439013
     0.00872646  0.02006321]]

  [[ 0.04525282  0.06494269  0.06061935  0.03535768 -0.03928109
    -0.00268092  0.01299914]]

  [[ 0.04445242  0.0655313   0.0547717   0.03485136 -0.03970576
    -0.00309531  0.01630875]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.02515619 -0.01467629  0.01744147 -0.03257047
    -0.025888    0

tf.Tensor(
[[[[ 0.02245624 -0.018404    0.05266027 -0.03213505  0.00064597
     0.06612454  0.02301113]]

  [[ 0.00718615 -0.02048945  0.04104437 -0.04841356 -0.01121222
     0.04800885  0.01139474]]

  [[-0.01070105 -0.02351352  0.02062778 -0.05681989 -0.0050076
     0.03645166  0.02019751]]]


 [[[-0.01863245 -0.04227875  0.00746772 -0.04006592  0.0154068
     0.03440909  0.02499406]]

  [[-0.02809891 -0.0410972  -0.00505748 -0.04222555  0.01191368
     0.01842908  0.01770387]]

  [[-0.04325312 -0.0364545  -0.01533866 -0.04673621  0.02158286
     0.00147076  0.01405865]]]


 [[[-0.04468201 -0.03602955 -0.02636399 -0.01811759  0.00193234
    -0.00859021  0.01177592]]

  [[-0.04867692 -0.03800627 -0.03386735 -0.01412335  0.00718799
    -0.0196422   0.00303249]]

  [[-0.05869876 -0.03728916 -0.03661375 -0.02171041  0.00268725
    -0.03179312 -0.00146637]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.         -0.018404    0.05266027 -0.03213505  0.00064597
     0.06612454  0.0

tf.Tensor(
[[[[-0.00000000e+00  9.71175171e-03 -1.49995163e-02 -1.33013353e-02
    -2.99167316e-02 -3.37266661e-02 -2.07870118e-02]]

  [[-1.45736840e-02  1.26172602e-02 -2.28342079e-02 -3.72355618e-03
    -4.33823727e-02 -3.69922854e-02 -3.12396488e-03]]

  [[-0.00000000e+00  1.02010854e-02 -2.37633996e-02 -1.20573863e-03
    -5.01674376e-02 -3.36316861e-02 -5.74004278e-03]]]


 [[[ 2.40614079e-03  1.90938786e-02 -6.86235540e-03 -1.37600675e-03
    -8.98990966e-03 -2.56387889e-02 -9.07313079e-03]]

  [[ 4.45563160e-03  2.53665093e-02 -8.28405097e-03  6.73436746e-03
    -8.24320596e-05 -3.13560739e-02 -4.31289058e-03]]

  [[ 2.97711045e-03  1.75181292e-02 -8.27728957e-03  9.47029889e-03
    -4.36916854e-03 -2.64691897e-02 -1.23239923e-02]]]


 [[[ 0.00000000e+00  3.36801969e-02  5.38166519e-03  1.03991795e-02
    -5.67457825e-02 -1.52160050e-02  1.10863382e-03]]

  [[ 2.50540879e-02  3.40856947e-02  1.01374825e-02  2.26538405e-02
    -4.34653126e-02 -2.17525046e-02 -5.45133371e-03]]

 

tf.Tensor(
[[[[-0.01266567 -0.01993449 -0.00665007  0.00013901  0.02254709
    -0.00103611 -0.00526203]]

  [[-0.00367223 -0.0051812  -0.00858585  0.01348948  0.00754622
     0.00891342  0.00580969]]

  [[ 0.01962981  0.01780201 -0.00241712  0.0338267   0.01959765
     0.02891356  0.00332366]]]


 [[[-0.01565135 -0.03366787 -0.02129703 -0.00169657  0.03418941
     0.00446882 -0.0053385 ]]

  [[-0.0055708  -0.02003994 -0.01734272  0.00330127  0.03010013
     0.02060362  0.00424018]]

  [[ 0.01748275  0.00066327 -0.00601343  0.01991815  0.02859386
     0.03787545 -0.00541938]]]


 [[[-0.02482786 -0.04117863 -0.02779581  0.00055488  0.00815898
     0.00823865 -0.00948068]]

  [[-0.01654336 -0.03324889 -0.02809095  0.00549875  0.00753862
     0.02282505 -0.00504094]]

  [[-0.00020253 -0.01637636 -0.02011039  0.01457245 -0.01205256
     0.03919572 -0.00663488]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.01993449 -0.00665007  0.00013901  0.02254709
    -0.00103611 -0

tf.Tensor(
[[[[ 0.01180712  0.0263633   0.0164703   0.02406605  0.02844768
     0.00366049  0.00507341]]

  [[ 0.00318784  0.02104052  0.00676466  0.019269    0.0179812
    -0.00526244  0.0091811 ]]

  [[ 0.00579731  0.02035881  0.00593913  0.02219862  0.03725882
     0.00059751  0.00151432]]]


 [[[ 0.01610809  0.014917    0.02152166  0.00883943  0.03864013
     0.01487126 -0.00215631]]

  [[ 0.01432035  0.01909497  0.01383936  0.0153721   0.0387475
     0.01367233 -0.00165525]]

  [[ 0.01233833  0.02753506  0.02080893  0.02428307  0.04443754
     0.02070719 -0.01879981]]]


 [[[ 0.01607089 -0.0016323   0.00713471 -0.00615681  0.03151808
     0.03296144 -0.00819683]]

  [[ 0.01568284  0.01601623  0.00464621  0.00592335  0.04305782
     0.02993429 -0.01655675]]

  [[ 0.01187281  0.02580251  0.02446693  0.01905498  0.0250949
     0.03718156 -0.02487792]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.0263633   0.0164703   0.02406605  0.02844768
     0.00366049  0.00

tf.Tensor(
[[[[-0.03330055 -0.02797003 -0.03412953 -0.01909779 -0.0115684
    -0.02190389 -0.0026401 ]]

  [[-0.02599652 -0.02583939 -0.03049767 -0.01946456 -0.01655537
    -0.01807512  0.00533911]]

  [[-0.02057141 -0.01691056 -0.01956551 -0.02177158 -0.01804474
    -0.0181962  -0.00547075]]]


 [[[-0.02453431 -0.00339213 -0.02485754 -0.00382694  0.00288699
    -0.03797365 -0.00093753]]

  [[-0.02029443 -0.00367476 -0.02540983 -0.00651434  0.00293212
    -0.03382484  0.00390123]]

  [[-0.0212817   0.0001348  -0.02028038 -0.00716336 -0.00683055
    -0.03280495 -0.01416322]]]


 [[[-0.0032093   0.0213882  -0.00071013  0.01084192 -0.0388133
    -0.04619929 -0.00155157]]

  [[-0.00338684  0.02294363 -0.00203989  0.00703969 -0.03391049
    -0.04440478 -0.00857217]]

  [[-0.00710989  0.02412465 -0.00310428  0.00146791 -0.0308156
    -0.0408074  -0.02383998]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.02797003 -0.03412953 -0.01909779 -0.0115684
    -0.02190389 -0.002

tf.Tensor(
[[[[ 0.00733438  0.01453915  0.04094165  0.01432418  0.08873413
     0.04165909 -0.00111282]]

  [[-0.00265022 -0.00350993  0.01486417 -0.00490446  0.06293691
     0.01739693 -0.00162609]]

  [[-0.01177475 -0.00286124 -0.00648943 -0.01408196  0.08825573
     0.00890731 -0.00652109]]]


 [[[-0.00753513  0.00835121  0.02578724  0.01452379  0.05633214
     0.0167231   0.00795906]]

  [[-0.01543317 -0.00881648  0.00602804  0.00203598  0.04224964
     0.00245923  0.00036237]]

  [[-0.01773234 -0.01009953 -0.00592549 -0.00459482  0.06046544
    -0.00449105 -0.01971172]]]


 [[[-0.00421997  0.00274802  0.02656059  0.01431713  0.06774523
     0.00756469 -0.00336712]]

  [[-0.01214262 -0.01542639  0.00750248  0.008238    0.0702707
     0.002894   -0.01332626]]

  [[-0.0198897  -0.01694473 -0.00726531  0.00178706  0.04655587
     0.01069747 -0.02211572]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.01453915  0.04094165  0.01432418  0.08873413
     0.04165909 -0.

tf.Tensor(
[[[[ 0.03072459  0.01387804  0.01569931  0.0300053  -0.01577519
     0.0253574  -0.00085566]]

  [[ 0.03687882  0.01876642  0.01899978  0.02190712 -0.02202807
     0.02853421  0.00143531]]

  [[ 0.03670839  0.0327334   0.02712991  0.02048422 -0.01543574
     0.03143813 -0.00838091]]]


 [[[ 0.01982827 -0.00486982  0.01586529  0.01284353  0.00633031
     0.02863274 -0.00238983]]

  [[ 0.02408443  0.00418101  0.01072675  0.00854567  0.00989938
     0.03318136  0.00093317]]

  [[ 0.03018828  0.02539841  0.01707875  0.01927189  0.01153461
     0.03045607 -0.0171635 ]]]


 [[[ 0.00066948 -0.01436873  0.01407473  0.00211003 -0.01885638
     0.02922233 -0.01624555]]

  [[ 0.01392752 -0.0007668   0.00515807  0.00012759 -0.01658621
     0.02976901 -0.01671856]]

  [[ 0.02489533  0.02211394  0.01184127  0.01931859 -0.01748777
     0.02970066 -0.03253793]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.01387804  0.01569931  0.0300053  -0.01577519
     0.0253574  -0

tf.Tensor(
[[[[-1.1999627e-02  1.3028346e-02 -3.5113979e-02  1.0311571e-02
     2.7599083e-03 -6.7769396e-03 -1.0832460e-02]]

  [[-5.0517172e-04  1.2186773e-02 -1.6199056e-02  2.8183876e-02
    -1.0951337e-02  1.5249003e-02  1.2135126e-02]]

  [[-3.1997375e-03  2.3066159e-03  1.7098006e-02  1.8494384e-02
    -9.6331351e-05  1.9095158e-02  3.0831780e-02]]]


 [[[ 8.5138828e-03  3.2437637e-02 -1.6448889e-02  1.4730909e-02
     1.5083804e-02  5.4944688e-03 -1.7990148e-02]]

  [[ 1.1075113e-02  3.4890745e-02  1.1948328e-02  3.0114086e-02
     1.4289938e-02  2.0625120e-02  3.9614122e-03]]

  [[-3.1707622e-04  1.8352482e-02  3.7556265e-02  2.6119802e-02
     1.6552724e-02  2.1639850e-02  1.5036860e-02]]]


 [[[ 2.4118161e-02  5.1282477e-02  3.8331747e-03  2.0950569e-02
    -1.9461066e-03  8.8752583e-03 -2.3098255e-02]]

  [[ 2.3418151e-02  5.4187551e-02  3.7393048e-02  3.7665591e-02
    -1.6083494e-03  2.2959076e-02 -5.6879995e-03]]

  [[ 1.3573032e-02  3.2867480e-02  5.2191682e-02  4.07214

tf.Tensor(
[[[[ 0.03247166  0.01166929  0.02442347  0.01297784  0.03900701
     0.03291121 -0.00134265]]

  [[ 0.02722117  0.01352445  0.00987918  0.00757993  0.01021088
     0.02806137 -0.000877  ]]

  [[ 0.03002588  0.01997036 -0.00145952  0.00952701  0.02708463
     0.04700152  0.00817417]]]


 [[[ 0.02043829 -0.0069497   0.01759879  0.01142838  0.04977167
     0.03523544  0.00191175]]

  [[ 0.01163371 -0.00623083 -0.00411199  0.0045878   0.04188277
     0.03078333  0.00011796]]

  [[ 0.00635042  0.00080764 -0.01313519  0.00908938  0.05070253
     0.03550027  0.01127295]]]


 [[[ 0.00764864 -0.0191099   0.01344335  0.00773221  0.0398
     0.03670532  0.00152646]]

  [[-0.00621743 -0.02397147 -0.01406593  0.00263383  0.04677711
     0.02892603 -0.00342136]]

  [[-0.01345462 -0.02219049 -0.02821998  0.0073646   0.03644446
     0.02767244  0.00338031]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.01166929  0.02442347  0.01297784  0.03900701
     0.03291121 -0.001

tf.Tensor(
[[[[ 0.00819399 -0.00149935  0.00988939 -0.0177783  -0.01633846
     0.00820166 -0.01199455]]

  [[-0.00346006 -0.00559643  0.0027322  -0.03074826 -0.02407659
    -0.00408312 -0.00131827]]

  [[-0.00673872 -0.00582135 -0.00587909 -0.03492609 -0.02400827
    -0.014273   -0.01321496]]]


 [[[ 0.00432784 -0.0078691   0.0030312  -0.0209091   0.02268734
    -0.0015073   0.00680973]]

  [[-0.0016553  -0.00671735 -0.00295064 -0.03012746  0.013246
    -0.01419476  0.00597243]]

  [[-0.00724412 -0.01094631 -0.00729743 -0.02751792 -0.00075221
    -0.01912699 -0.01860419]]]


 [[[ 0.00236505 -0.00681402 -0.00028469 -0.02099923 -0.00676672
    -0.00364004  0.008498  ]]

  [[-0.00206952 -0.00519383 -0.00266251 -0.02528376 -0.01301637
    -0.01797174 -0.00099431]]

  [[-0.00274783 -0.00819898 -0.00450453 -0.01548159 -0.03023321
    -0.02469025 -0.02289471]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.         -0.00149935  0.00988939 -0.0177783  -0.01633846
     0.00820166 -0.0

tf.Tensor(
[[[[ 0.01601077  0.02685453  0.03757339 -0.01267059 -0.06765511
     0.02956077  0.00429239]]

  [[ 0.00894481  0.02032013  0.04310068 -0.00443351 -0.08166242
     0.0241132   0.01186285]]

  [[ 0.01503074  0.01987453  0.037515    0.00179948 -0.05569148
     0.01333414  0.0167461 ]]]


 [[[ 0.01457486  0.02206741  0.02504015 -0.01204741 -0.0114841
     0.02940111  0.01631016]]

  [[ 0.01374274  0.01570939  0.02659863 -0.01066331  0.01037665
     0.02319372  0.01154453]]

  [[ 0.01444288  0.01090555  0.02764037 -0.00803451  0.02691866
     0.01664332  0.00116523]]]


 [[[ 0.0138527   0.01819501  0.020074   -0.00922264 -0.05225398
     0.02244705  0.00653728]]

  [[ 0.01415612  0.00881511  0.01920589 -0.01505647 -0.01245632
     0.01664596  0.00092559]]

  [[ 0.01010042  0.00525942  0.02526833 -0.01150795  0.00755094
     0.01172396 -0.00443606]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.02685453  0.03757339 -0.01267059 -0.06765511
     0.02956077  0.

tf.Tensor(
[[[[-3.70152341e-03 -1.51993986e-02  1.01749245e-02  5.93500212e-03
    -1.56919509e-02  1.88705921e-02 -2.74537075e-02]]

  [[-8.44808109e-03 -1.61750168e-02 -4.43547033e-03 -2.78452691e-03
    -4.10441123e-02  8.35248642e-03 -6.70201285e-03]]

  [[-6.39847014e-04 -4.14976850e-04 -6.00483222e-03  6.05925824e-03
    -2.95276344e-02 -1.72242569e-03 -3.39877456e-02]]]


 [[[ 1.82604184e-03 -1.67794637e-02  1.60565116e-02  3.17032076e-03
     1.85971279e-02  1.32509498e-02 -2.24739313e-02]]

  [[-3.92292487e-03 -7.41838850e-03 -7.77136302e-04  5.84840402e-03
     1.39891086e-02 -4.57685441e-04 -1.53216003e-02]]

  [[ 8.75457004e-03  6.04077429e-03 -4.58113151e-03  1.19095435e-02
     1.37642967e-02 -9.13082622e-05 -5.69818690e-02]]]


 [[[-3.55566852e-04 -2.42396593e-02  7.71001400e-03 -2.12809490e-03
     7.66029954e-03  1.50871929e-02 -2.28749812e-02]]

  [[-8.12926330e-04 -4.04190458e-03 -3.25426832e-03  6.53119525e-03
     5.23201376e-03  4.17232886e-03 -4.37591374e-02]]

 

tf.Tensor(
[[[[-0.02236919 -0.01495361  0.00518069 -0.00131542  0.04100739
     0.00564088 -0.00176932]]

  [[-0.03469359 -0.02126153  0.00059903 -0.01437061  0.01410865
    -0.00088381  0.0079172 ]]

  [[-0.0379369  -0.01849487 -0.01077919 -0.01213075  0.01177695
    -0.00302746  0.01317373]]]


 [[[-0.01811125 -0.00438442  0.01387153 -0.00627146  0.00980022
    -0.00071469  0.00497882]]

  [[-0.02861182 -0.01363007  0.00902389 -0.02122884  0.01988813
    -0.01759575 -0.00088445]]

  [[-0.03433678 -0.01356028 -0.00759507 -0.01899476  0.03737867
    -0.01569786 -0.0133064 ]]]


 [[[-0.01269622 -0.00261784  0.02041259 -0.03524576 -0.02407247
    -0.00450275  0.00196947]]

  [[-0.02002084 -0.00825724  0.01737951 -0.0435133   0.01452239
    -0.01315399 -0.01397343]]

  [[-0.02172189 -0.01351667  0.00592827 -0.03679605  0.03542765
    -0.00959531 -0.02812467]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.01495361  0.00518069 -0.00131542  0.04100739
     0.00564088 -0

tf.Tensor(
[[[[ 0.0066272   0.02719263  0.00962515  0.01154006 -0.01806542
     0.00036595  0.00414222]]

  [[ 0.01907328  0.02693538  0.02046835  0.02458913 -0.0494172
     0.01472641  0.00014661]]

  [[ 0.03051094  0.0201554   0.03056418  0.031516   -0.07589115
     0.01746463  0.00047528]]]


 [[[ 0.01730167  0.02766047  0.01069892  0.01226113  0.0032216
     0.02319932  0.00329121]]

  [[ 0.03252656  0.02856465  0.02983176  0.01633847 -0.00600663
     0.02691493 -0.00104638]]

  [[ 0.04708179  0.03021356  0.04282018  0.01995227 -0.03401626
     0.02741639 -0.0126904 ]]]


 [[[ 0.01991589  0.02625315  0.01650109  0.01039251 -0.03745237
     0.02780812  0.01399507]]

  [[ 0.0346103   0.03518737  0.03422289  0.00911709 -0.05396198
     0.03665558  0.00680607]]

  [[ 0.04771009  0.04445637  0.04887448  0.01112605 -0.06425501
     0.02562038 -0.01175465]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.02719263  0.00962515  0.01154006 -0.01806542
     0.00036595  0.0

tf.Tensor(
[[[[-0.01544506 -0.01473938 -0.01252909 -0.03104652  0.08234008
     0.00615845 -0.008619  ]]

  [[-0.0154145  -0.014339   -0.02013853 -0.02865243  0.06987205
    -0.00241925  0.00407907]]

  [[-0.01350085 -0.01662108 -0.02663682 -0.02503452  0.09294274
    -0.0049293  -0.00590801]]]


 [[[-0.03370489 -0.02401748 -0.02816902 -0.03236379  0.05464222
    -0.01473906 -0.0056612 ]]

  [[-0.02932964 -0.0224845  -0.03495795 -0.03411767  0.04601876
    -0.01723172 -0.00402845]]

  [[-0.02137681 -0.01856789 -0.03988119 -0.03039929  0.06422298
    -0.01570731 -0.02232198]]]


 [[[-0.03642819 -0.02486623 -0.03343196 -0.02669317  0.06988655
    -0.01773132 -0.02562398]]

  [[-0.03600654 -0.02761321 -0.04434163 -0.02920352  0.07815279
    -0.02048006 -0.03420235]]

  [[-0.02657044 -0.02095647 -0.04830977 -0.02962283  0.07419561
    -0.00790112 -0.05021745]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.01473938 -0.01252909 -0.03104652  0.08234008
     0.00615845 -0

tf.Tensor(
[[[[ 0.03187954  0.02513207  0.01009988  0.03940999  0.0336772
     0.00855665 -0.00499613]]

  [[ 0.01870515  0.0080435   0.00202226  0.03485188  0.01171071
     0.00180934 -0.00170163]]

  [[ 0.00567079 -0.00854955 -0.00594832  0.01966724  0.03439327
    -0.01066055 -0.00239162]]]


 [[[ 0.03031135  0.02365697  0.01086976  0.04353599  0.02523744
     0.02236683  0.02194856]]

  [[ 0.01484688  0.00168339  0.00543832  0.02482843  0.04424151
     0.00905148  0.01368365]]

  [[ 0.00516353 -0.01333093 -0.00394144  0.00599025  0.06849371
    -0.00393532 -0.00296841]]]


 [[[ 0.02680626  0.01558031  0.01551789  0.04043359 -0.00924364
     0.02586707  0.01654881]]

  [[ 0.01344819 -0.00509505  0.00925503  0.01343017  0.03476113
     0.01586624  0.00948317]]

  [[-0.00096227 -0.00738424 -0.00425724 -0.00213694  0.04497823
    -0.00249306 -0.00209302]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.02513207  0.01009988  0.03940999  0.0336772
     0.00855665 -0.0

tf.Tensor(
[[[[-0.01639769 -0.01818835  0.00615639 -0.01098991 -0.05312769
    -0.01185228  0.00755823]]

  [[-0.0256818  -0.02267238 -0.0041694  -0.01541518 -0.04889804
    -0.01818401  0.01037218]]

  [[-0.03085414 -0.02171027 -0.01625943 -0.02042065 -0.05040509
    -0.02431272  0.00744429]]]


 [[[-0.01228723 -0.00465367  0.01103489 -0.00514259 -0.02977553
    -0.01332058  0.01564925]]

  [[-0.0154361  -0.01051689  0.00286793 -0.0048795  -0.01227293
    -0.02070339  0.01114537]]

  [[-0.01941147 -0.01095238 -0.00885499 -0.00790508 -0.01951073
    -0.0276099  -0.00141378]]]


 [[[-0.00317188  0.00700866  0.01545194 -0.00110891 -0.08161947
    -0.01118756  0.01270804]]

  [[-0.0014176   0.00562333  0.01361651  0.0035993  -0.06102078
    -0.02151846  0.00648845]]

  [[-0.00622136  0.00419533  0.0044372  -0.00113881 -0.04949269
    -0.02734491  0.00467169]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.01818835  0.00615639 -0.01098991 -0.05312769
    -0.01185228  0

tf.Tensor(
[[[[ 0.05628718  0.04234811  0.07632953  0.04220492 -0.06691347
     0.04209009  0.00837329]]

  [[ 0.04618914  0.04281744  0.05599775  0.02326928 -0.07267755
     0.03236669  0.00465351]]

  [[ 0.04359709  0.05202712  0.04715607  0.01284256 -0.06695039
     0.02282936 -0.01744856]]]


 [[[ 0.05470261  0.04537661  0.07473165  0.02973763 -0.01701735
     0.04677437  0.01810749]]

  [[ 0.04592222  0.04369726  0.05771744  0.01683873 -0.01848159
     0.03462336  0.0093527 ]]

  [[ 0.04473052  0.04420105  0.05151562  0.01299801 -0.024899
     0.03081265 -0.02210844]]]


 [[[ 0.04668095  0.03838912  0.06463458  0.02101077 -0.06129388
     0.04856367  0.03321984]]

  [[ 0.04343733  0.0411206   0.05280343  0.01382955 -0.07206607
     0.0391788   0.02059082]]

  [[ 0.04320548  0.03752583  0.04608208  0.01187503 -0.07362034
     0.02997123 -0.0082062 ]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.04234811  0.07632953  0.04220492 -0.06691347
     0.04209009  0.0

tf.Tensor(
[[[[ 0.00680486 -0.02823117  0.03711086  0.01625952  0.04865897
     0.04339956 -0.00538334]]

  [[-0.02750932 -0.06391725  0.02948718 -0.0263408   0.03598946
     0.02518838  0.01210589]]

  [[-0.06945343 -0.08396932 -0.00356496 -0.05350493  0.05981873
     0.00623393  0.00140559]]]


 [[[-0.00985239 -0.03828777  0.02214166  0.01682494  0.05552963
     0.02773366  0.01912923]]

  [[-0.04985139 -0.07382412  0.00611871 -0.02121879  0.04786158
    -0.00215202  0.0245388 ]]

  [[-0.09608994 -0.09815518 -0.03360057 -0.04242802  0.06790577
    -0.02276189 -0.02067862]]]


 [[[-0.02996388 -0.02913274  0.02566895  0.0227068   0.06603238
     0.00768244 -0.00436735]]

  [[-0.06709867 -0.06366043 -0.00335019 -0.00328228  0.07751521
    -0.02235992 -0.00730991]]

  [[-0.10408895 -0.09069739 -0.04781622 -0.02553483  0.07176904
    -0.04888145 -0.04894838]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.         -0.02823117  0.03711086  0.01625952  0.04865897
     0.04339956 -0

tf.Tensor(
[[[[ 0.03975646  0.00790094  0.03559524  0.0052862  -0.02195087
     0.02077736  0.00490514]]

  [[ 0.02293562 -0.00670619  0.02452956 -0.0205025  -0.04819105
     0.01418723  0.00909548]]

  [[ 0.00647251 -0.00441637  0.00859108 -0.01923606 -0.044186
     0.01404372 -0.00131011]]]


 [[[ 0.02821579 -0.00926417  0.0405662  -0.01003744  0.01108742
     0.02787796  0.01036913]]

  [[ 0.00903825 -0.01835816  0.02251395 -0.02002507 -0.00761576
     0.0243501   0.00827347]]

  [[-0.00387032 -0.02142091  0.00142859 -0.01399328 -0.02261825
     0.016219   -0.00495248]]]


 [[[ 0.01321298 -0.01666911  0.03469612 -0.00684697 -0.04992589
     0.02515801  0.03029784]]

  [[-0.0005456  -0.0301198   0.01934859 -0.01448934 -0.07495733
     0.01216912  0.02626419]]

  [[-0.01525165 -0.03494238 -0.00372398 -0.01398732 -0.0812961
     0.00029753  0.00303746]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.00790094  0.03559524  0.0052862  -0.02195087
     0.02077736  0.00

tf.Tensor(
[[[[-0.03165773 -0.02647005 -0.02731575 -0.03817019  0.04774413
    -0.01883549 -0.0071331 ]]

  [[-0.02689031 -0.02087952 -0.03246105 -0.03196865  0.03486917
    -0.02516927 -0.00239369]]

  [[-0.01968573 -0.0126493  -0.03049303 -0.02698706  0.04004669
    -0.02069163  0.00313992]]]


 [[[-0.02732863 -0.01738622 -0.03532092 -0.02619118  0.03300057
    -0.0282343  -0.00058133]]

  [[-0.02323803 -0.01063957 -0.03441229 -0.0231116   0.02864199
    -0.03000343 -0.00478699]]

  [[-0.01449198 -0.00461703 -0.0309116  -0.01914013  0.03378372
    -0.02602712 -0.00237591]]]


 [[[-0.01794947 -0.00677246 -0.02941262 -0.01553927  0.02396956
    -0.0299598  -0.00416156]]

  [[-0.01511177 -0.00164965 -0.02736779 -0.0147565   0.02786535
    -0.02829204 -0.0135107 ]]

  [[-0.00546723  0.00433368 -0.02176659 -0.01295272  0.02026274
    -0.02622773 -0.0117295 ]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.02647005 -0.02731575 -0.03817019  0.04774413
    -0.01883549 -0

tf.Tensor(
[[[[ 0.04316991  0.02930569  0.04430243  0.04031324 -0.02964504
     0.03112566 -0.01610203]]

  [[ 0.02713495  0.0103185   0.03378488  0.03361182 -0.03633113
     0.02107694  0.01665529]]

  [[ 0.00024219  0.00467444  0.01517763  0.02114332 -0.00265081
     0.00654547  0.01674558]]]


 [[[ 0.04321397  0.03101473  0.04212987  0.0361063   0.0222882
     0.0414664  -0.00443603]]

  [[ 0.03265091  0.01853964  0.03975628  0.04120784  0.0405267
     0.02784762  0.01013807]]

  [[ 0.01216921  0.0167674   0.02397294  0.04380378  0.0597031
     0.0067809  -0.00559515]]]


 [[[ 0.03913288  0.0343316   0.0261661   0.03202251 -0.02681304
     0.04601951 -0.01456303]]

  [[ 0.0317407   0.03579956  0.0375215   0.04548857 -0.00368855
     0.02805934 -0.01829199]]

  [[ 0.0218004   0.02999269  0.02964979  0.05673484  0.00862296
     0.00377867 -0.03289196]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.02930569  0.04430243  0.04031324 -0.02964504
     0.03112566 -0.01

tf.Tensor(
[[[[-3.31504196e-02 -7.79037364e-03 -6.09917007e-02 -1.41815664e-02
     7.98963010e-02 -1.28711369e-02 -1.09340400e-02]]

  [[-1.32636940e-02  5.31989988e-03 -3.94903496e-02  4.09239857e-03
     5.33284992e-02 -3.97730619e-05  2.41127959e-03]]

  [[-1.00628776e-03  7.77513441e-03 -1.78192928e-02  7.37412646e-03
     6.27264827e-02  2.98998272e-03 -1.51055455e-02]]]


 [[[-2.25860775e-02  5.36456937e-03 -5.50915301e-02  6.60543097e-03
     5.32653257e-02 -1.47994300e-02  1.34001533e-02]]

  [[-4.21617739e-03  1.09601272e-02 -3.04661635e-02  1.74323805e-02
     5.70905209e-02 -4.19263355e-03  8.90142005e-03]]

  [[ 1.06187409e-03  1.28746890e-02 -8.54257494e-03  1.40413530e-02
     6.42527640e-02  8.12169164e-04 -1.82523355e-02]]]


 [[[-2.19823606e-03  2.57362053e-02 -3.34026441e-02  1.83873102e-02
     3.15508805e-02 -1.87247917e-02  1.61423236e-02]]

  [[ 1.07158367e-02  2.17046067e-02 -1.35890413e-02  2.04764046e-02
     4.73375842e-02 -2.34728493e-03  1.47710275e-03]]

 

tf.Tensor(
[[[[-0.01102935  0.00588462 -0.0114605   0.00884776 -0.02587659
    -0.01567599  0.01069927]]

  [[-0.00167466  0.00983671 -0.01079347  0.00855289 -0.0476026
    -0.00017199  0.01762531]]

  [[ 0.00728931  0.01628658  0.00227536 -0.00213276 -0.03694967
     0.01277213  0.01870039]]]


 [[[ 0.00175511 -0.00054738  0.00720988 -0.00436972 -0.0034823
    -0.01094782  0.01384176]]

  [[ 0.0047144   0.00068528  0.00109746 -0.01331385 -0.02197256
     0.00375982  0.01783247]]

  [[ 0.00551967  0.00409429  0.00556448 -0.02051555 -0.03302521
     0.01635105  0.0240259 ]]]


 [[[ 0.010418   -0.01429643  0.01248392 -0.013809   -0.10811199
     0.00150245  0.01858615]]

  [[ 0.00436724 -0.01065063  0.00982692 -0.02022076 -0.13448806
     0.00737976  0.0245282 ]]

  [[-0.00014537 -0.00720168  0.00344257 -0.02057637 -0.13142045
     0.0162956   0.03332182]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.          0.00588462 -0.0114605   0.00884776 -0.02587659
    -0.01567599  0.0

tf.Tensor(
[[[[-2.6399987e-03  5.7847924e-03  1.2107659e-04 -1.3606958e-02
    -6.7672469e-02 -9.2236213e-03  8.8120196e-03]]

  [[ 2.2608533e-03  7.4188430e-03  7.9238536e-03 -1.0050617e-02
    -6.8273917e-02 -5.1920814e-03  1.4218148e-02]]

  [[ 1.6135529e-03  8.3092060e-03  1.9175597e-02 -1.2822413e-02
    -8.5641295e-02 -2.3511874e-03  1.7976895e-02]]]


 [[[-1.0269806e-03  1.0438869e-04  6.7063239e-03 -9.2843166e-03
    -2.4218543e-02 -3.8754987e-03  2.3403846e-02]]

  [[ 6.7224051e-03 -4.4055874e-03  1.1674787e-02 -1.0100730e-02
    -2.2422200e-02  3.4285514e-03  2.7494542e-02]]

  [[ 6.7014694e-03 -1.1103603e-02  1.7462544e-02 -1.5020552e-02
    -5.4409903e-02  1.2457447e-02  2.8148476e-02]]]


 [[[-3.3374140e-03 -9.6609816e-03  5.0472310e-03  2.0518305e-04
    -8.0797844e-02 -4.8938179e-03  3.5006579e-02]]

  [[-1.6430011e-03 -1.1839845e-02  1.0124218e-02  5.9410988e-04
    -9.8858401e-02  7.7306712e-04  3.9438944e-02]]

  [[-4.6549644e-03 -2.0925604e-02  8.8700382e-03 -7.02988

tf.Tensor(
[[[[-0.03836844 -0.01856881 -0.04204474  0.01270597 -0.00723561
    -0.02691754  0.0026315 ]]

  [[-0.03706004 -0.01966348 -0.0513662   0.00191987 -0.00561873
    -0.02408164 -0.00779381]]

  [[-0.03004241 -0.01830112 -0.05078238 -0.00156012  0.02772864
    -0.01684001 -0.03595478]]]


 [[[-0.00664183  0.01429529 -0.00453468  0.02836805  0.0112135
    -0.03556746 -0.02129973]]

  [[-0.00374246  0.01145964 -0.01402028  0.01873688  0.01414682
    -0.03359655 -0.03645466]]

  [[-0.00227286  0.00619368 -0.01946244  0.01369595  0.03414075
    -0.02326366 -0.07469222]]]


 [[[ 0.0208329   0.02915438  0.03450163  0.01059196  0.01721548
    -0.01694898 -0.05445505]]

  [[ 0.02152131  0.02699905  0.02268587  0.00707127  0.00915461
    -0.01860193 -0.08980352]]

  [[ 0.0241421   0.02301681  0.01547094  0.00130959  0.02059307
    -0.01462081 -0.11570453]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.01856881 -0.04204474  0.01270597 -0.00723561
    -0.02691754  0.

tf.Tensor(
[[[[-0.0131648  -0.0017436  -0.02488099  0.02482198  0.08058614
    -0.01353325  0.00433461]]

  [[-0.02248451 -0.01655795 -0.03037447  0.02547251  0.07508875
    -0.02450914  0.01407492]]

  [[-0.02829232 -0.01535699 -0.03305267  0.0251513   0.10147363
    -0.04017926  0.00212415]]]


 [[[-0.0036972   0.00741905 -0.01832743  0.04598472  0.05350261
    -0.0102646   0.01771828]]

  [[-0.0129443   0.00040536 -0.02500606  0.03066419  0.06149364
    -0.01684987  0.02068651]]

  [[-0.02038211 -0.00083452 -0.02950932  0.02726911  0.0847635
    -0.02474232 -0.00502271]]]


 [[[ 0.01789613  0.01778753  0.00349124  0.04424329  0.04519149
    -0.00965198  0.02108344]]

  [[ 0.00423126  0.01627746 -0.00498769  0.03026794  0.07207507
    -0.01005381  0.0203627 ]]

  [[-0.00627355  0.0152441  -0.01212433  0.02509193  0.07879812
    -0.00889969 -0.00165889]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.0017436  -0.02488099  0.02482198  0.08058614
    -0.01353325  0.

tf.Tensor(
[[[[ 6.1521148e-03  3.6203684e-03  5.7619065e-05  1.4163312e-03
    -8.5751593e-02  2.8764181e-02 -3.4912587e-03]]

  [[ 1.2240957e-02  7.2539155e-03  1.1659393e-02  3.5867919e-03
    -1.1125697e-01  3.1118255e-02  4.8386161e-03]]

  [[ 7.8736320e-03  4.5596366e-03  2.4598124e-02  1.8641618e-03
    -1.3626343e-01  2.7532417e-02  2.8053178e-03]]]


 [[[-8.4436564e-03 -1.5617870e-02 -1.2549395e-02 -1.0473640e-02
    -3.2186635e-02  2.1779262e-02  1.6803309e-02]]

  [[ 7.6808827e-04 -6.3196872e-03 -5.4447725e-04 -8.2876049e-03
    -3.5179794e-02  2.4528243e-02  1.1842316e-02]]

  [[ 3.8413485e-03 -6.5532033e-03  1.1829179e-02  3.2849982e-03
    -5.8744483e-02  2.2157107e-02  8.8463910e-04]]]


 [[[-2.2611259e-02 -2.0860754e-02 -1.9867089e-02 -7.5358646e-03
    -9.7241916e-02  5.0452491e-03  3.3591740e-02]]

  [[-1.7743457e-02 -1.8458951e-02 -1.5185751e-02 -3.5533183e-03
    -1.0147224e-01  1.0951434e-02  2.6755571e-02]]

  [[-9.2570987e-03 -1.5836466e-02 -5.9074461e-03  1.36726

tf.Tensor(
[[[[-0.03463588 -0.01757732 -0.03835652 -0.0099507   0.03449602
    -0.02929696 -0.02271993]]

  [[-0.03002572 -0.01660036 -0.04392506 -0.00682385  0.01692899
    -0.02796006  0.00386115]]

  [[-0.02263056 -0.01064334 -0.03622881 -0.00022536  0.02359421
    -0.02122132  0.00414068]]]


 [[[-0.02532707 -0.00173318 -0.03505107 -0.00306     0.02963227
    -0.02471696 -0.00361535]]

  [[-0.01589882  0.00112102 -0.03071701 -0.0087501   0.03156345
    -0.02495996  0.00173093]]

  [[-0.01133932  0.01170983 -0.01933062 -0.0026503   0.03842025
    -0.01499515 -0.01592777]]]


 [[[-0.00866307  0.01237162 -0.01370086 -0.00016241  0.00074098
    -0.02943951 -0.00767511]]

  [[ 0.00117996  0.01899932 -0.00718209 -0.00767506  0.02345415
    -0.01955319 -0.01602711]]

  [[ 0.0099107   0.02836863  0.00315168 -0.00103618  0.02353346
    -0.00527031 -0.02573479]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.01757732 -0.03835652 -0.0099507   0.03449602
    -0.02929696 -0

tf.Tensor(
[[[[-0.01910283 -0.00056636 -0.02685586 -0.00107131 -0.06984486
    -0.01106412 -0.01290573]]

  [[-0.00019516  0.01520978 -0.0097089   0.01661854 -0.07915793
     0.00295122  0.0056919 ]]

  [[ 0.01144785  0.03125097  0.00882789  0.01784101 -0.07886885
     0.01079419  0.00106941]]]


 [[[-0.00349567  0.01724555 -0.0132707   0.02717295 -0.01452064
    -0.01503167 -0.00880944]]

  [[ 0.01233171  0.02888273  0.00403056  0.03722747 -0.02660333
    -0.00421445 -0.00261559]]

  [[ 0.02128096  0.03501046  0.02280043  0.03666433 -0.035422
     0.01352131 -0.01124649]]]


 [[[ 0.01935476  0.03809836  0.01539346  0.04080042 -0.10675809
    -0.00790414  0.013607  ]]

  [[ 0.03382376  0.0409454   0.02513697  0.0468781  -0.13163082
     0.01542065  0.01411617]]

  [[ 0.04016315  0.04822995  0.04087965  0.04319308 -0.12615715
     0.0278143   0.00777504]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.00056636 -0.02685586 -0.00107131 -0.06984486
    -0.01106412 -0.0

tf.Tensor(
[[[[-5.2248100e-03  8.2605751e-03 -7.2656157e-03  5.3122863e-03
     2.4210388e-02 -1.5446572e-02 -3.1612148e-03]]

  [[ 7.2801495e-03  6.6368924e-03 -8.3228359e-03  1.2173835e-02
     2.1818833e-02 -1.1499649e-02  6.6445377e-03]]

  [[ 2.1131409e-02 -1.6324320e-03 -1.8019481e-03  1.8149421e-02
     1.5858743e-02  6.4752409e-03  6.7232186e-03]]]


 [[[ 4.4075409e-03  1.8832268e-02 -2.8343713e-03  1.0273402e-02
     3.3128373e-02 -2.2248846e-02  1.2155836e-02]]

  [[ 6.0687913e-03  9.4844894e-03  1.6812235e-05  1.4939657e-02
     1.7328644e-02 -1.5823487e-02  1.6171834e-02]]

  [[ 1.4799656e-02  5.2993898e-03  2.4607386e-03  1.7354507e-02
     3.0821728e-02 -1.5503310e-03  4.4806227e-03]]]


 [[[ 1.7906189e-02  1.6849613e-02  1.5437191e-02 -9.6288510e-05
     2.2425205e-02 -1.5365984e-02  1.3481125e-02]]

  [[ 1.2459132e-02  1.0892846e-02  1.6458485e-02  4.7692191e-03
     4.2239316e-03 -8.7603368e-03  1.4752002e-02]]

  [[ 8.2050757e-03  7.5969286e-03  1.7483056e-02  6.90436

tf.Tensor(
[[[[-0.         -0.00239614 -0.02864164 -0.02675794 -0.02195549
    -0.0026689  -0.02109188]]

  [[-0.00361858  0.01400312 -0.01916287 -0.01605867 -0.02820988
    -0.00390189 -0.00669545]]

  [[ 0.          0.0129076  -0.01213127 -0.00705207 -0.03146704
    -0.002591   -0.00423056]]]


 [[[-0.01094207 -0.00043425 -0.03007653 -0.02375702  0.00753573
    -0.00242554 -0.01488329]]

  [[ 0.00095858  0.01468646 -0.02017634 -0.01155927  0.004923
    -0.00526595 -0.01351355]]

  [[ 0.0072672   0.01369981 -0.00952791 -0.00374338  0.00018312
    -0.00883053 -0.02230279]]]


 [[[-0.          0.00459779 -0.031031   -0.01355126 -0.00299284
    -0.00835897 -0.0315244 ]]

  [[ 0.00141844  0.01448404 -0.02297742 -0.0071761  -0.00033228
    -0.00573014 -0.03380132]]

  [[ 0.          0.01586609 -0.01023031  0.00071203 -0.00016414
    -0.00711593 -0.04006203]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.01337725 -0.0032331  -0.01120419 -0.00319217  0.05333614
     0.00962887 -0.0

tf.Tensor(
[[[[-0.0254878  -0.02056929  0.01474346 -0.03594299  0.02627271
     0.00069381 -0.02683997]]

  [[-0.03291195 -0.02199087  0.00564152 -0.0362818   0.01458387
    -0.00237337 -0.00503082]]

  [[-0.0411808  -0.02802106 -0.0091401  -0.03185744  0.01782887
    -0.01016834 -0.00062093]]]


 [[[-0.02800452 -0.01953196  0.0077455  -0.02888262  0.01220369
    -0.00492574 -0.00029496]]

  [[-0.02831617 -0.01905387  0.0016909  -0.02488633  0.03172528
    -0.01002353 -0.00677651]]

  [[-0.03302027 -0.01977943 -0.00598257 -0.01463553  0.04989254
    -0.01695455 -0.02316542]]]


 [[[-0.03361005 -0.0117013  -0.01004335 -0.02093768 -0.00708672
    -0.01474863 -0.0173579 ]]

  [[-0.02683939 -0.00638056 -0.00908115 -0.01215228  0.03960429
    -0.01901443 -0.03820705]]

  [[-0.02282942 -0.00206908 -0.00564077 -0.00094531  0.05314244
    -0.02022182 -0.05063543]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.02056929  0.01474346 -0.03594299  0.02627271
     0.00069381 -0

tf.Tensor(
[[[[-0.01737855 -0.02262693 -0.00831594 -0.02064196  0.05430017
     0.01724986 -0.01592163]]

  [[-0.02094798 -0.02960811 -0.01517756 -0.0238869   0.05240122
     0.00688515  0.00454301]]

  [[-0.01882436 -0.02229303 -0.02605443 -0.00982395  0.06797703
     0.00750427  0.00188021]]]


 [[[-0.02033141 -0.025594   -0.01240577 -0.02729073  0.03265366
    -0.00446775 -0.01514612]]

  [[-0.0181404  -0.02752486 -0.02052123 -0.03243031  0.03330768
    -0.00842557 -0.01267571]]

  [[-0.01671313 -0.01509694 -0.03079918 -0.01594477  0.04508178
    -0.01045133 -0.02722567]]]


 [[[-0.02416914 -0.0244066  -0.01034234 -0.03144639  0.04377278
    -0.01878784 -0.03798901]]

  [[-0.0174375  -0.02101411 -0.01942618 -0.03568723  0.03701723
    -0.01852721 -0.05176066]]

  [[-0.01844582 -0.01071698 -0.02635659 -0.02328772  0.042153
    -0.01367629 -0.05532692]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.02262693 -0.00831594 -0.02064196  0.05430017
     0.01724986 -0.0

tf.Tensor(
[[[[ 0.01884582  0.0050028   0.00960129  0.0039848  -0.06623175
     0.00423065 -0.0125683 ]]

  [[ 0.02599449  0.00530225  0.01855633  0.00065261 -0.05582257
     0.00847162  0.00618966]]

  [[ 0.02571424  0.00563645  0.02264236 -0.00304177 -0.03178703
     0.01310119 -0.0024581 ]]]


 [[[ 0.00504854 -0.00402373  0.00227139 -0.0015848   0.00382685
     0.00870974 -0.00814734]]

  [[ 0.00502834 -0.00384989  0.00397901 -0.00361254  0.01862964
     0.0110423   0.00202319]]

  [[ 0.00544802 -0.00479279  0.01281423 -0.00187513  0.03486436
     0.01564467 -0.01704931]]]


 [[[-0.00930102 -0.00582735 -0.00517222  0.00290022 -0.02096028
     0.01105804  0.00046891]]

  [[-0.01170558 -0.01057764 -0.00593355  0.00339208  0.00199809
     0.00883741 -0.01278969]]

  [[-0.01003218 -0.00899636 -0.00393711  0.00186715  0.01174622
     0.00888524 -0.03135591]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.0050028   0.00960129  0.0039848  -0.06623175
     0.00423065 -0

tf.Tensor(
[[[[-0.0015111   0.00392067  0.01405637  0.00910759 -0.07444198
    -0.03205228  0.03188392]]

  [[ 0.00331596  0.00683321  0.00465114  0.01502522 -0.09632221
    -0.01599764  0.0326863 ]]

  [[ 0.01212025  0.00164944  0.01139552  0.01551588 -0.09791739
    -0.00682308  0.03812071]]]


 [[[ 0.00857874 -0.0055353   0.02377744 -0.00513887 -0.02299117
    -0.01025295  0.04514956]]

  [[ 0.00930079 -0.00170627  0.01446085  0.00242869 -0.03100319
    -0.00264927  0.04314814]]

  [[ 0.0115324  -0.00320304  0.01623368  0.0088093  -0.03028922
     0.00483063  0.0571243 ]]]


 [[[ 0.00153488 -0.01804775  0.01199331 -0.00743144 -0.10665788
    -0.00080999  0.0555604 ]]

  [[ 0.00304883 -0.01482921  0.00389008  0.00361518 -0.09565422
    -0.0034628   0.06192631]]

  [[ 0.00700925 -0.00944585  0.00743052  0.0129644  -0.07313169
    -0.00421649  0.08559957]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.          0.00392067  0.01405637  0.00910759 -0.07444198
    -0.03205228  0

tf.Tensor(
[[[[-0.01882611 -0.0087421  -0.02861566 -0.0081618   0.04046895
     0.00038574 -0.00979001]]

  [[-0.00605777  0.0040231  -0.01682306  0.00600797 -0.00278735
    -0.00280794 -0.0044005 ]]

  [[ 0.00462366  0.02031223 -0.00459238  0.01807253 -0.01212963
    -0.0077511  -0.025288  ]]]


 [[[-0.01951817 -0.01011982 -0.0375113  -0.00886027  0.04222162
     0.00141538  0.00821671]]

  [[-0.00533501 -0.00599995 -0.0233726  -0.00134656  0.01639147
    -0.00429475 -0.00809407]]

  [[ 0.00490555  0.0115962  -0.00519565  0.01218689  0.01387396
    -0.00164169 -0.03274634]]]


 [[[-0.01777268 -0.01203723 -0.02709313  0.00442153  0.00603627
    -0.00876544  0.0070791 ]]

  [[-0.00919286 -0.01000891 -0.01732199  0.00565648  0.00950122
     0.00071752 -0.01245133]]

  [[-0.00077936 -0.00182193 -0.00647674  0.01258376  0.00961152
     0.00710429 -0.02599186]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.0087421  -0.02861566 -0.0081618   0.04046895
     0.00038574 -0

tf.Tensor(
[[[[ 0.00989892  0.00799979  0.00394297  0.01711315 -0.01028619
    -0.01539906  0.00439909]]

  [[ 0.01109718 -0.00483511  0.00212485  0.01173888 -0.00521881
    -0.00703555  0.01598785]]

  [[ 0.0036193  -0.01398179  0.0013889   0.00681255  0.01072258
    -0.00182486  0.01631718]]]


 [[[ 0.00915172 -0.00502189  0.00522586  0.01174135  0.0165959
     0.0030767   0.0099456 ]]

  [[ 0.00092001 -0.01718359  0.0031911   0.00879053  0.03349116
     0.00794752  0.01396348]]

  [[-0.00758406 -0.02205722 -0.00242723  0.00035732  0.05245266
     0.00915099  0.00961758]]]


 [[[-0.003486   -0.01555087  0.00250172  0.00804253  0.00583442
     0.01137288  0.00139807]]

  [[-0.01253183 -0.01643642 -0.00244979  0.00662417  0.03962202
     0.00814546 -0.00220688]]

  [[-0.01967657 -0.01763574 -0.01370198  0.00437533  0.05611537
     0.00035799 -0.00056358]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.00799979  0.00394297  0.01711315 -0.01028619
    -0.01539906  0.

tf.Tensor(
[[[[ 0.00015527 -0.00738962  0.00116942 -0.02447974 -0.0212119
     0.00631474 -0.0029205 ]]

  [[-0.00311932 -0.00995509 -0.00103435 -0.02585613 -0.00864369
     0.00751618  0.00489826]]

  [[-0.0041767  -0.01140419  0.00270846 -0.02376767  0.00461169
     0.01167395 -0.00842954]]]


 [[[-0.00829072 -0.00900881  0.00285159 -0.02524763 -0.00908345
     0.00058302 -0.00503702]]

  [[-0.01122034 -0.01025321 -0.00093937 -0.02783862  0.01378141
     0.00337942 -0.00482337]]

  [[-0.01145064 -0.01167106  0.00091527 -0.02323901  0.01663776
     0.00616759 -0.02953333]]]


 [[[-0.01125432 -0.01388659  0.00037549 -0.02330471 -0.01858773
    -0.00383567 -0.02296357]]

  [[-0.01471632 -0.01208981 -0.00326945 -0.02355639  0.00567725
    -0.00076465 -0.0330147 ]]

  [[-0.01339488 -0.01087122 -0.00387321 -0.01764302  0.02269264
     0.00201343 -0.04723284]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.         -0.00738962  0.00116942 -0.02447974 -0.0212119
     0.00631474 -0.0

tf.Tensor(
[[[[ 5.25875390e-03 -2.13121325e-02  7.01663271e-03 -7.32660294e-04
     1.00202657e-01  9.77524649e-03 -1.70934014e-02]]

  [[-1.10059045e-03 -2.06192508e-02  3.71515751e-04 -1.14150327e-02
     8.04801434e-02  9.93904099e-03 -3.64479912e-03]]

  [[-1.95720373e-03 -1.30155608e-02 -5.67398872e-03 -1.54610835e-02
     8.85409191e-02  1.91137604e-02 -1.27694635e-02]]]


 [[[-1.05084032e-02 -3.24007832e-02 -1.28218783e-02 -1.04555981e-02
     5.37142120e-02  3.41210701e-03 -6.66181883e-03]]

  [[-1.65286660e-02 -2.68174261e-02 -2.30108500e-02 -1.52676906e-02
     4.74846736e-02  3.57330311e-03 -8.75808485e-03]]

  [[-1.44157466e-02 -1.51459910e-02 -2.61262320e-02 -1.47328228e-02
     5.65907285e-02 -3.85819003e-05 -3.99699360e-02]]]


 [[[-1.65302437e-02 -2.47492362e-02 -2.05239803e-02 -7.45621976e-03
     4.92612012e-02 -6.40818523e-03 -2.11728830e-02]]

  [[-1.79364365e-02 -1.87085979e-02 -3.15153822e-02 -8.95150565e-03
     6.02331944e-02 -1.17674824e-02 -4.12940681e-02]]

 

tf.Tensor(
[[[[-0.00628166 -0.00375918 -0.00222795 -0.00639132  0.06113876
    -0.01224928 -0.03357511]]

  [[-0.01202846 -0.00507207 -0.01126904 -0.00750588  0.03338746
    -0.01751368 -0.00866223]]

  [[-0.00503601  0.00377157 -0.01713488 -0.00439246  0.04542097
    -0.01457421 -0.01062564]]]


 [[[-0.00550875  0.00573554 -0.0037177  -0.00462378  0.06448387
    -0.01510874 -0.00757834]]

  [[-0.00917915  0.00118921 -0.00945333 -0.00183546  0.05603459
    -0.02247234 -0.00368337]]

  [[-0.00297843  0.00673336 -0.0169875   0.00080999  0.06815213
    -0.01842035 -0.0244778 ]]]


 [[[-0.00186356  0.00608566 -0.00197836  0.00507874  0.05440482
    -0.00948709 -0.00448751]]

  [[-0.0031308   0.00838798 -0.00436905  0.00261852  0.07306316
    -0.01737854 -0.00990314]]

  [[ 0.00249801  0.01105822 -0.01002957  0.00377718  0.07423352
    -0.0107528  -0.02444488]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.00375918 -0.00222795 -0.00639132  0.06113876
    -0.01224928 -0

tf.Tensor(
[[[[ 0.00967468  0.00049914  0.01774241 -0.00739331 -0.04876322
     0.00935647 -0.00570996]]

  [[ 0.00515548 -0.00478791  0.00636691 -0.01821069 -0.02315392
    -0.00140935 -0.00264439]]

  [[-0.00136595 -0.00603322 -0.00563568 -0.01998614  0.00025656
    -0.00518195 -0.00373009]]]


 [[[ 0.00237593 -0.00307129  0.00850306 -0.0100917  -0.02523554
     0.00351082  0.00145125]]

  [[-0.0031068  -0.0089537  -0.00268274 -0.01653283  0.00238639
    -0.00388515 -0.0011075 ]]

  [[-0.00801034 -0.0092151  -0.01122905 -0.01476758  0.01546772
    -0.00957148 -0.0060316 ]]]


 [[[-0.00449063 -0.00465814  0.00102852 -0.00538756 -0.04379113
    -0.00107894 -0.00311483]]

  [[-0.00824631 -0.00989674 -0.0069763  -0.01052057 -0.01894891
    -0.00586691 -0.00998527]]

  [[-0.0103856  -0.01133883 -0.01389848 -0.00776122 -0.00504304
    -0.00903544 -0.01513023]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.00049914  0.01774241 -0.00739331 -0.04876322
     0.00935647 -0

tf.Tensor(
[[[[-0.00635603 -0.00808911  0.0033132   0.01300111 -0.07489512
     0.02878464  0.02449899]]

  [[-0.00924138 -0.00724909  0.00663609  0.02604871 -0.1189855
     0.02723216  0.0245864 ]]

  [[-0.00883013 -0.01106465  0.01455795  0.0206146  -0.12854739
     0.01470913  0.02926072]]]


 [[[-0.00244503 -0.00847927  0.00231913  0.00954374 -0.00932791
     0.01258177  0.02261506]]

  [[-0.00619079 -0.01148696  0.00577564  0.02425183 -0.04115386
     0.00847023  0.01981494]]

  [[-0.01086859 -0.01873829  0.0082484   0.02356937 -0.08701286
     0.00122256  0.00313564]]]


 [[[-0.0034104  -0.00837309 -0.00314853  0.01678513 -0.07626076
    -0.00194049  0.00561508]]

  [[-0.00335045 -0.01216056  0.00020598  0.02946497 -0.12707375
    -0.00359661 -0.00241954]]

  [[-0.01054894 -0.01570291  0.00398009  0.02198884 -0.14980504
    -0.01075239 -0.00788609]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.00808911  0.0033132   0.01300111 -0.07489512
     0.02878464  0.

tf.Tensor(
[[[[ 0.00391461 -0.00912807 -0.01531679 -0.01615699  0.0952158
    -0.00282406 -0.03137226]]

  [[-0.00562709 -0.01310983 -0.02120319 -0.02333036  0.083648
    -0.00465663 -0.01403717]]

  [[-0.00835838 -0.00528326 -0.02400199 -0.01641619  0.0995587
     0.00484702 -0.01983852]]]


 [[[ 0.00130163 -0.01212907 -0.01359496 -0.01481449  0.05570573
    -0.00755103 -0.01259118]]

  [[-0.01099053 -0.01371708 -0.02212298 -0.01787756  0.05850553
    -0.01285095 -0.01097051]]

  [[-0.01039977 -0.00796292 -0.02726611 -0.00880277  0.08765967
    -0.00884931 -0.02744291]]]


 [[[ 0.00130899 -0.01648267 -0.01807593 -0.01575517  0.0413265
    -0.00970124 -0.01721365]]

  [[-0.00879152 -0.01889062 -0.02782276 -0.01415249  0.06041216
    -0.01889319 -0.02749387]]

  [[-0.01066745 -0.01529879 -0.03461818 -0.00860537  0.08059818
    -0.01991737 -0.04423557]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.         -0.00912807 -0.01531679 -0.01615699  0.0952158
    -0.00282406 -0.03137

tf.Tensor(
[[[[-0.01001352 -0.00790784 -0.01072633  0.00350019 -0.00106996
    -0.01364714  0.00525126]]

  [[-0.01440828 -0.00780252 -0.02162902 -0.00515692 -0.03258323
    -0.01605185  0.00187499]]

  [[-0.01742613 -0.00134333 -0.02377726 -0.00770755 -0.02704133
    -0.02299662  0.0040829 ]]]


 [[[-0.007353   -0.00265225 -0.0061261   0.00201199  0.02556031
    -0.01591158  0.01054946]]

  [[-0.00913335 -0.00203383 -0.01728719 -0.00541843 -0.00274529
    -0.02200633  0.00396422]]

  [[-0.01225227  0.00267869 -0.01830122 -0.00459321 -0.00922611
    -0.02189764 -0.00293098]]]


 [[[-0.0071059   0.00243228  0.00013183  0.00146209 -0.02547724
    -0.01663449  0.02943156]]

  [[-0.0036738   0.0044687  -0.00731981 -0.00424813 -0.06007126
    -0.02380951  0.02509179]]

  [[-0.00473764  0.00836221 -0.00866741 -0.00237833 -0.0891505
    -0.01993737  0.0141314 ]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.00790784 -0.01072633  0.00350019 -0.00106996
    -0.01364714  0.

tf.Tensor(
[[[[ 0.0254822   0.00268275  0.01158985  0.0051775  -0.01769745
     0.02326445  0.015557  ]]

  [[ 0.02186172 -0.00339533  0.00730225 -0.006874   -0.00282331
     0.02406605  0.01365274]]

  [[ 0.012272   -0.0001324   0.00455669 -0.01006774  0.01996155
     0.02870572  0.02331079]]]


 [[[ 0.00729269 -0.0120652   0.00064993 -0.00655103 -0.00165694
     0.02098086  0.02294521]]

  [[-0.00441781 -0.0148668  -0.0047388  -0.01346054  0.03491881
     0.01952036  0.02129531]]

  [[-0.00969117 -0.00031651 -0.0046408  -0.01485039  0.06532799
     0.01249281  0.00919625]]]


 [[[-0.00711108 -0.01443734 -0.00839945 -0.00899996  0.00863092
     0.0173945   0.01688294]]

  [[-0.01659309 -0.0108467  -0.00895495 -0.01532692  0.06559546
     0.01517274  0.01384905]]

  [[-0.01627475  0.00240989 -0.0120991  -0.01402806  0.10613273
     0.00856727  0.00122841]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[ 0.          0.00268275  0.01158985  0.0051775  -0.01769745
     0.02326445  0

tf.Tensor(
[[[[-0.02511755 -0.01860208 -0.0235028   0.02812295  0.16007149
     0.01106211 -0.02952186]]

  [[-0.03949982 -0.02413171 -0.03810616  0.01646731  0.12021022
    -0.0072433  -0.00770207]]

  [[-0.04601236 -0.01996912 -0.05002514  0.00714856  0.14217573
    -0.02472847 -0.04339962]]]


 [[[-0.01521549 -0.0036999  -0.02155411  0.02705328  0.12010957
     0.01623749 -0.01456654]]

  [[-0.03208803 -0.01403215 -0.03394219  0.01458514  0.09290589
    -0.00996    -0.01639973]]

  [[-0.0415959  -0.01821404 -0.04912509  0.00676213  0.12568818
    -0.02265118 -0.0768591 ]]]


 [[[-0.00211304  0.01009263 -0.01084751  0.02378734  0.1339966
     0.02511233 -0.03744314]]

  [[-0.01593583 -0.00178774 -0.01868857  0.01297444  0.13845764
    -0.00295132 -0.06896844]]

  [[-0.02522913 -0.00153495 -0.03010942  0.00376617  0.13587952
    -0.01779789 -0.11311142]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.         -0.01860208 -0.0235028   0.02812295  0.16007149
     0.01106211 -0.

tf.Tensor(
[[[[-0.01089256  0.0047249   0.00284178  0.02395399 -0.03679017
     0.00948394  0.02708428]]

  [[-0.01758306 -0.00280725 -0.00138626  0.03655989 -0.03684434
     0.0023242   0.01938102]]

  [[-0.02233167 -0.00610543  0.00146374  0.03882252 -0.01616044
    -0.00434577  0.01204461]]]


 [[[ 0.00117146  0.01198914  0.01877805  0.02186871 -0.00577759
     0.00921215  0.02267309]]

  [[-0.00103121  0.01130502  0.01176283  0.03353123  0.0023427
     0.0061607   0.02225424]]

  [[-0.00250089  0.00028662  0.01007761  0.04065751  0.00193496
     0.00507501  0.01950604]]]


 [[[ 0.01413459  0.01385211  0.02389465  0.01647531 -0.04655089
     0.01215433  0.02378407]]

  [[ 0.01534049  0.00999869  0.01772012  0.02122744 -0.04825669
     0.00838621  0.02376891]]

  [[ 0.01269411 -0.00562333  0.01077774  0.02674115 -0.04430749
     0.00968217  0.02835767]]]], shape=(3, 3, 1, 7), dtype=float32)
tf.Tensor(
[[[[-0.          0.0047249   0.00284178  0.02395399 -0.03679017
     0.00948394  0.

In [95]:
def x(*args):
    print(*args)
x(1, 1)

1 1


In [109]:
x = (2, 3)
print(*x)

2 3
